package br.com.zup.talkaboutcats.utils

const val NAME_ERROR_MESSAGE = "Favor informar nome"
const val EMAIL_ERROR_MESSAGE = "Favor informar email"
const val PASSWORD_ERROR_MESSAGE = "Favor informar senha"
const val REGISTER_ERROR_MESSAGE = "Não foi possivel realizar o registro"
const val LOGIN_ERROR_MESSAGE = "Não foi possivel realizar o login!"
const val USER_KEY = "USER"
const val ERROR_VALIDATE_NAME = "Seu nome deve ter no mínimo 3 caracteres"
const val ERROR_VALIDATE_PASSWORD = "Sua senha deve conter no mínimo 8 caracteres"
const val INVALID_EMAIL = "E-mail inválido"
const val REGISTER = "Registro"
const val LOGIN = "Login"
const val EMAIL_REGEX= "^[A-Za-z](.*)([@]{1})(.{1,})(\\.)(.{1,})"
const val FACT_KEY = "catfacts"